"use client";

import Navbar from '@/components/layout/Navbar';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Download, Printer, ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { useFirebase } from '@/firebase/provider';
import AuthGuard from '@/components/auth/AuthGuard';
import Image from 'next/image';

const QR_CODES = [
    { name: 'ComLab 1', file: '/qr-codes/qr-comlab-1.png' },
    { name: 'ComLab 2', file: '/qr-codes/qr-comlab-2.png' },
    { name: 'Multimedia Lab', file: '/qr-codes/qr-multimedia-lab.png' },
    { name: 'Network Lab', file: '/qr-codes/qr-network-lab.png' },
    { name: 'Hardware Lab', file: '/qr-codes/qr-hardware-lab.png' },
];

export default function QRDownloadsPage() {
    return (
        <AuthGuard requiredRole="admin">
            <QRDownloadsContent />
        </AuthGuard>
    );
}

function QRDownloadsContent() {
    const { user } = useFirebase();

    const currentUser = {
        displayName: user?.displayName || 'Admin',
        email: user?.email || '',
        role: 'admin' as const,
        photoURL: user?.photoURL || undefined,
    };

    const handleDownload = (file: string, name: string) => {
        const link = document.createElement('a');
        link.href = file;
        link.download = `QR-${name.replace(/\s+/g, '-')}.png`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    const handlePrint = () => {
        window.print();
    };

    return (
        <div className="min-h-screen bg-black print:bg-white print:text-black">
            <div className="print:hidden">
                <Navbar user={currentUser} />
            </div>

            <main className="container mx-auto px-4 py-8 space-y-8">
                <div className="flex items-center justify-between print:hidden">
                    <div className="space-y-1">
                        <div className="flex items-center gap-2 mb-2">
                            <Link href="/admin" className="text-zinc-400 hover:text-white transition-colors">
                                <ArrowLeft className="h-5 w-5" />
                            </Link>
                            <h1 className="text-3xl font-bold tracking-tight text-white font-headline">Room QR Codes</h1>
                        </div>
                        <p className="text-zinc-500">Download and print QR codes for laboratory access points.</p>
                    </div>
                    <Button variant="outline" onClick={handlePrint} className="gap-2 bg-zinc-900 border-zinc-800 text-zinc-300 hover:bg-zinc-800 hover:text-white">
                        <Printer className="h-4 w-4" />
                        Print All
                    </Button>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 print:grid-cols-2 print:gap-8">
                    {QR_CODES.map((qr) => (
                        <Card key={qr.name} className="bg-zinc-950 border-zinc-800 shadow-xl print:shadow-none print:border-black/20 print:bg-white">
                            <CardHeader className="text-center pb-2">
                                <CardTitle className="text-xl text-white font-bold print:text-black">{qr.name}</CardTitle>
                                <CardDescription className="text-zinc-500 print:text-gray-500">Scan to check-in/out</CardDescription>
                            </CardHeader>
                            <CardContent className="flex flex-col items-center gap-6 pb-6">
                                <div className="bg-white p-4 rounded-xl shadow-inner border border-zinc-200">
                                    <div className="relative w-48 h-48">
                                        <Image
                                            src={qr.file}
                                            alt={`QR Code for ${qr.name}`}
                                            fill
                                            className="object-contain"
                                        />
                                    </div>
                                </div>

                                <Button
                                    className="w-full gap-2 bg-zinc-100 text-black hover:bg-zinc-200 font-bold print:hidden"
                                    onClick={() => handleDownload(qr.file, qr.name)}
                                >
                                    <Download className="h-4 w-4" />
                                    Download Image
                                </Button>
                            </CardContent>
                        </Card>
                    ))}
                </div>

                <div className="hidden print:block text-center mt-12 text-sm text-gray-400">
                    Generated by NEU Laboratory Log Management System
                </div>
            </main>
        </div>
    );
}
